runtime: nodejs12

service: steakeye-web-ui

instance_class: F1

automatic_scaling:
  max_instances: 1

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301